version: '3.8'

services:
  devserver:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "3.10"
        # Optional Node.js version to install
        NODE_VERSION: "none"

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs devserver on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    networks:
    - proxy-net
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
    ports:
    - "2222:22"
    # Use "forwardPorts" in **devcontainer.json** to forward an devserver port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
networks:
  proxy-net:
    external:
      name: airflow_default