# [Choice] Python version (use -bullseye variants on local arm64/Apple Silicon): 3, 3.10, 3.9, 3.8, 3.7, 3.6, 3-bullseye, 3.10-bullseye, 3.9-bullseye, 3.8-bullseye, 3.7-bullseye, 3.6-bullseye, 3-buster, 3.10-buster, 3.9-buster, 3.8-buster, 3.7-buster, 3.6-buster
ARG VARIANT=3-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

ENV PYTHONUNBUFFERED 1

# [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
ARG NODE_VERSION="none"
RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

#[Optional] Uncomment this section to install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends iputils-ping

RUN useradd -rm -d /home/ssh_user -s /bin/bash ssh_user && \
    echo ssh_user:ssh_user1234 | chpasswd

RUN mkdir /home/ssh_user/.ssh && \
    chmod 700 /home/ssh_user/.ssh

COPY id_rsa.pub /home/ssh_user/.ssh/authorized_keys

RUN chown ssh_user:ssh_user -R /home/ssh_user/.ssh && \
    chmod 600 /home/ssh_user/.ssh/authorized_keys


